remote_theme: kjartankg/front-cover

name: Kjartan Mýrdal
#description: "Nifty little description"

github_username: kjartankg
linkedin_username: kmyrdal

front_img: yes
front_img_path: "imgs/backgr.jpg"